import 'spec.dart';

/// Emits records.g.dart: ByteData codecs with the endianness stated explicitly
/// at every call, sentinel-aware nullable accessors (a detached probe is
/// structurally incapable of surfacing as 0), and pack/unpack for the
/// variable-length BLE payloads.
String emitDart(ProtocolSpec spec) {
  final b = StringBuffer();
  b.writeln('// GENERATED by tools/protogen from protocol/records.yaml — DO NOT EDIT.');
  b.writeln('// Regenerate with: dart run protogen   (CI fails on any diff)');
  b.writeln('//');
  b.writeln('// Little-endian wire format throughout. See protocol/records.yaml for');
  b.writeln('// field semantics and design 04 §4.2 / 05 §5.6 for rationale.');
  b.writeln('// ignore_for_file: unnecessary_library_name');
  b.writeln('library records_g;');
  b.writeln();
  b.writeln("import 'dart:convert';");
  b.writeln("import 'dart:typed_data';");
  b.writeln();

  _emitConstants(spec, b);
  _emitCrc(spec, b);
  _emitStringHelpers(b);
  _emitEnums(spec, b);

  for (final r in spec.records) {
    if (r.isFixed || (r.isControlBody && !r.hasVariableFields)) {
      _emitFixedRecord(spec, r, b);
    } else {
      _emitVarRecord(spec, r, b);
    }
  }
  return b.toString();
}

String _camel(String snake) {
  final parts = snake.split('_').where((p) => p.isNotEmpty).toList();
  return parts.first + parts.skip(1).map(_cap).join();
}

String _cap(String s) => s[0].toUpperCase() + s.substring(1);

String _pascal(String snake) => snake.split('_').map(_cap).join();

String _className(RecordSpec r) {
  if (r.isControlBody) return 'Ctrl${_pascal(r.name)}';
  if (r.name == 'result') return 'ResultFrame';
  return _pascal(r.name);
}

String _enumClass(String specName) =>
    specName == 'units' ? 'TempUnits' : _pascal(specName);

void _emitConstants(ProtocolSpec spec, StringBuffer b) {
  b.writeln('// ── Constants ──────────────────────────────────────────────────');
  b.writeln();
  spec.constants.forEach((name, value) {
    final id = _camel(name.toLowerCase());
    if (value is String) {
      b.writeln("const String $id = '$value';");
    } else {
      b.writeln('const int $id = $value;');
    }
  });
  b.writeln();
}

void _emitCrc(ProtocolSpec spec, StringBuffer b) {
  if (spec.crc16['refin'] != 0 || spec.crc32['refin'] != 1) {
    throw SpecException('crc emitter expects CCITT-FALSE / ISO-HDLC shapes');
  }
  final poly16 =
      '0x${spec.crc16['poly']!.toRadixString(16).toUpperCase().padLeft(4, '0')}';
  final poly32r = '0x${_reflect32(spec.crc32['poly']!).toRadixString(16).toUpperCase()}';
  b.writeln('''
// ── CRC-16/CCITT-FALSE and CRC-32/ISO-HDLC ─────────────────────────

int crc16Update(int crc, Uint8List data, int start, int end) {
  for (var i = start; i <= end; i++) {
    crc ^= data[i] << 8;
    for (var bit = 0; bit < 8; bit++) {
      crc = (crc & 0x8000) != 0 ? ((crc << 1) ^ $poly16) & 0xFFFF : (crc << 1) & 0xFFFF;
    }
  }
  return crc;
}

/// check("123456789") == 0x29B1
int crc16CcittFalse(Uint8List data, [int start = 0, int? end]) =>
    crc16Update(0xFFFF, data, start, (end ?? data.length) - 1);

int crc32Update(int state, Uint8List data, int start, int end) {
  for (var i = start; i <= end; i++) {
    state ^= data[i];
    for (var bit = 0; bit < 8; bit++) {
      state = (state & 1) != 0 ? (state >>> 1) ^ $poly32r : state >>> 1;
    }
  }
  return state;
}

/// check("123456789") == 0xCBF43926
int crc32IsoHdlc(Uint8List data, [int start = 0, int? end]) =>
    (crc32Update(0xFFFFFFFF, data, start, (end ?? data.length) - 1) ^ 0xFFFFFFFF) >>> 0;
''');
}

int _reflect32(int v) {
  var r = 0;
  for (var i = 0; i < 32; i++) {
    r = (r << 1) | ((v >> i) & 1);
  }
  return r;
}

void _emitStringHelpers(StringBuffer b) {
  b.writeln('''
// ── NUL-padded UTF-8 helpers ───────────────────────────────────────

/// Decodes a NUL-padded UTF-8 byte region into a String (empty if malformed).
String utf8FromPadded(Uint8List bytes) {
  var end = bytes.indexOf(0);
  if (end < 0) end = bytes.length;
  try {
    return utf8.decode(bytes.sublist(0, end));
  } on FormatException {
    return '';
  }
}

/// Encodes [s] as UTF-8 into a NUL-padded buffer of [length] bytes.
/// Throws [ArgumentError] if the encoded form does not fit.
Uint8List utf8ToPadded(String s, int length) {
  final enc = utf8.encode(s);
  if (enc.length > length) {
    throw ArgumentError.value(s, 's', 'does not fit in \$length bytes as UTF-8');
  }
  final out = Uint8List(length);
  out.setRange(0, enc.length, enc);
  return out;
}
''');
}

void _emitEnums(ProtocolSpec spec, StringBuffer b) {
  b.writeln('// ── Enums (wire values) ────────────────────────────────────────');
  b.writeln();
  spec.enums.forEach((name, values) {
    final cls = _enumClass(name);
    b.writeln('enum $cls {');
    final entries = values.entries.toList();
    for (var i = 0; i < entries.length; i++) {
      final sep = i == entries.length - 1 ? ';' : ',';
      b.writeln('  ${_camel(entries[i].key)}(${entries[i].value})$sep');
    }
    b.writeln();
    b.writeln('  const $cls(this.wire);');
    b.writeln('  final int wire;');
    b.writeln();
    b.writeln('  static $cls? fromWire(int v) {');
    b.writeln('    for (final e in values) {');
    b.writeln('      if (e.wire == v) {');
    b.writeln('        return e;');
    b.writeln('      }');
    b.writeln('    }');
    b.writeln('    return null;');
    b.writeln('  }');
    b.writeln('}');
    b.writeln();
  });
}

bool _isLengthField(RecordSpec r, FieldSpec f) =>
    r.fields.any((o) => o.varLenField == f.name);

void _emitCrcFn(RecordSpec r, FieldSpec f, StringBuffer b) {
  final fn = '${_camel(r.name)}Crc';
  if (f.crc!.kind == 'crc16') {
    b.writeln('/// ${f.crc!.kind} of a wire-format ${r.name}, per records.yaml coverage.');
    b.writeln('int $fn(Uint8List buf, [int offset = 0]) {');
    b.writeln('  var c = 0xFFFF;');
    for (final range in f.crc!.ranges) {
      b.writeln('  c = crc16Update(c, buf, offset + ${range.start}, offset + ${range.end});');
    }
    b.writeln('  return c;');
    b.writeln('}');
  } else {
    b.writeln('/// ${f.crc!.kind} of a wire-format ${r.name}, per records.yaml coverage.');
    b.writeln('int $fn(Uint8List buf, [int offset = 0]) {');
    b.writeln('  var s = 0xFFFFFFFF;');
    for (final range in f.crc!.ranges) {
      b.writeln('  s = crc32Update(s, buf, offset + ${range.start}, offset + ${range.end});');
    }
    b.writeln('  return (s ^ 0xFFFFFFFF) >>> 0;');
    b.writeln('}');
  }
  b.writeln();
}

void _emitFixedRecord(ProtocolSpec spec, RecordSpec r, StringBuffer b) {
  final cls = _className(r);
  final size = r.declaredSize ??
      r.fields.fold<int>(0, (a, f) => a + f.type.size * f.count * f.rows);
  final crcField = r.fields.where((f) => f.crc != null).firstOrNull;

  for (final f in r.fields.where((f) => f.crc != null)) {
    _emitCrcFn(r, f, b);
  }

  b.writeln('/// ${r.name} — fixed $size B.${r.isControlBody ? ' (device_control body)' : ''}');
  b.writeln('class $cls {');
  b.writeln('  $cls({');
  for (final f in r.fields) {
    if (f.crc != null) {
      b.writeln('    this.${_camel(f.name)} = 0,');
    } else if (_isChar(f)) {
      b.writeln('    Uint8List? ${_camel(f.name)}Raw,');
    } else if (f.count > 1) {
      b.writeln('    List<int>? ${_camel(f.name)},');
    } else if (f.constValue is int) {
      b.writeln('    this.${_camel(f.name)} = ${f.constValue},');
    } else {
      b.writeln('    this.${_camel(f.name)} = 0,');
    }
  }
  final inits = <String>[];
  for (final f in r.fields) {
    final n = _camel(f.name);
    if (_isChar(f)) {
      if (f.rows > 1) {
        inits.add('${n}Raw = ${n}Raw ?? Uint8List(${f.rows * f.count})');
      } else {
        inits.add(f.constValue is String
            ? "${n}Raw = ${n}Raw ?? utf8ToPadded('${f.constValue}', ${f.count})"
            : '${n}Raw = ${n}Raw ?? Uint8List(${f.count})');
      }
    } else if (f.count > 1 && f.crc == null) {
      inits.add('$n = $n ?? List<int>.filled(${f.count}, 0)');
    }
  }
  if (inits.isEmpty) {
    b.writeln('  });');
  } else {
    b.writeln('  })  : ${inits.join(',\n        ')};');
  }
  b.writeln();
  b.writeln('  static const int size = $size;');
  b.writeln();
  for (final f in r.fields) {
    final n = _camel(f.name);
    final doc = f.doc != null ? '  /// ${f.doc}\n' : '';
    if (_isChar(f)) {
      b.write(doc);
      b.writeln('  final Uint8List ${n}Raw;');
    } else if (f.count > 1) {
      b.write(doc);
      b.writeln('  final List<int> $n;');
    } else {
      b.write(doc);
      b.writeln('  final int $n;');
    }
  }
  b.writeln();

  // Derived accessors: strings, sentinels, bits, enums.
  for (final f in r.fields) {
    final n = _camel(f.name);
    if (_isChar(f)) {
      if (f.rows > 1) {
        b.writeln('  List<String> get $n => [');
        b.writeln('        for (var i = 0; i < ${f.rows}; i++)');
        b.writeln('          utf8FromPadded(Uint8List.sublistView(${n}Raw, i * ${f.count}, (i + 1) * ${f.count})),');
        b.writeln('      ];');
      } else {
        b.writeln('  String get $n => utf8FromPadded(${n}Raw);');
      }
    }
    if (f.sentinel != null) {
      b.writeln();
      b.writeln('  /// null when the wire value is a sentinel (detached/invalid) —');
      b.writeln('  /// a detached probe must never surface as a number.');
      if (f.count > 1 || f.isVariable) {
        b.writeln('  int? ${n}OrNull(int i) {');
        b.writeln('    final v = $n[i];');
        b.writeln('    return v == tempDetached || v == tempInvalid ? null : v;');
        b.writeln('  }');
        b.writeln();
        b.writeln('  List<int?> get ${n}Nullable =>');
        b.writeln('      [for (var i = 0; i < $n.length; i++) ${n}OrNull(i)];');
        b.writeln();
        b.writeln('  bool ${n}IsDetached(int i) => $n[i] == tempDetached;');
        b.writeln('  bool ${n}IsInvalid(int i) => $n[i] == tempInvalid;');
      }
    }
    if (f.bits != null) {
      b.writeln();
      for (var i = 0; i < f.bits!.length; i++) {
        final bit = f.bits![i];
        if (bit.startsWith('_')) continue;
        b.writeln('  bool get ${_camel(bit)} => ($n & (1 << $i)) != 0;');
      }
    }
    if (f.enumName != null) {
      final cls = _enumClass(f.enumName!);
      if (f.count > 1) {
        b.writeln('  List<$cls?> get ${n}Enum => '
            '[for (final v in $n) $cls.fromWire(v)];');
      } else {
        b.writeln('  $cls? get ${n}Enum => $cls.fromWire($n);');
      }
    }
  }
  b.writeln();

  // decode
  b.writeln('  /// Parses $size wire bytes at [offset]. Never rejects on version;');
  b.writeln('  /// check [crcOk]${r.name == 'session_header' ? ' and [magicOk]' : ''} after decoding.');
  b.writeln('  factory $cls.decode(Uint8List buf, [int offset = 0]) {');
  b.writeln('    final bd = ByteData.sublistView(buf, offset, offset + size);');
  b.writeln('    return $cls(');
  for (final f in r.fields) {
    final n = _camel(f.name);
    final off = f.offset!;
    if (_isChar(f)) {
      b.writeln('      ${n}Raw: Uint8List.fromList(Uint8List.sublistView('
          'buf, offset + $off, offset + $off + ${f.rows * f.count})),');
    } else if (f.count > 1) {
      b.writeln('      $n: [');
      b.writeln('        for (var i = 0; i < ${f.count}; i++)');
      b.writeln('          ${_bdGet(f.type, '$off + i * ${f.type.size}')},');
      b.writeln('      ],');
    } else {
      b.writeln('      $n: ${_bdGet(f.type, '$off')},');
    }
  }
  b.writeln('    );');
  b.writeln('  }');
  b.writeln();

  // encode
  b.writeln('  /// Serializes to $size wire bytes${crcField != null ? ', computing the CRC' : ''}.');
  b.writeln('  Uint8List encode() {');
  b.writeln('    final out = Uint8List(size);');
  b.writeln('    final bd = ByteData.sublistView(out);');
  for (final f in r.fields) {
    if (f.crc != null) continue;
    final n = _camel(f.name);
    final off = f.offset!;
    if (_isChar(f)) {
      b.writeln('    out.setRange($off, $off + ${f.rows * f.count}, ${n}Raw);');
    } else if (f.count > 1) {
      b.writeln('    for (var i = 0; i < ${f.count}; i++) {');
      b.writeln('      ${_bdSet(f.type, '$off + i * ${f.type.size}', '$n[i]')};');
      b.writeln('    }');
    } else {
      b.writeln('    ${_bdSet(f.type, '$off', n)};');
    }
  }
  if (crcField != null) {
    final fn = '${_camel(r.name)}Crc';
    b.writeln('    ${_bdSet(crcField.type, '${crcField.offset}', '$fn(out)')};');
  }
  b.writeln('    return out;');
  b.writeln('  }');
  if (crcField != null) {
    b.writeln();
    b.writeln('  /// Whether the stored ${_camel(crcField.name)} matches the field bytes.');
    b.writeln('  bool get crcOk => ${_camel(crcField.name)} == ${_camel(r.name)}Crc(encode());');
  }
  if (r.name == 'session_header') {
    b.writeln();
    b.writeln("  bool get magicOk => magic == sessionMagic;");
  }
  b.writeln('}');
  b.writeln();
}

bool _isChar(FieldSpec f) => f.type == WireType.char;

String _bdGet(WireType t, String off) => switch (t) {
      WireType.u8 => 'bd.getUint8($off)',
      WireType.i8 => 'bd.getInt8($off)',
      WireType.u16 => 'bd.getUint16($off, Endian.little)',
      WireType.i16 => 'bd.getInt16($off, Endian.little)',
      WireType.u32 => 'bd.getUint32($off, Endian.little)',
      WireType.i32 => 'bd.getInt32($off, Endian.little)',
      WireType.u64 => 'bd.getUint64($off, Endian.little)',
      WireType.i64 => 'bd.getInt64($off, Endian.little)',
      WireType.char => 'bd.getUint8($off)',
    };

String _bdSet(WireType t, String off, String v) => switch (t) {
      WireType.u8 => 'bd.setUint8($off, $v)',
      WireType.i8 => 'bd.setInt8($off, $v)',
      WireType.u16 => 'bd.setUint16($off, $v, Endian.little)',
      WireType.i16 => 'bd.setInt16($off, $v, Endian.little)',
      WireType.u32 => 'bd.setUint32($off, $v, Endian.little)',
      WireType.i32 => 'bd.setInt32($off, $v, Endian.little)',
      WireType.u64 => 'bd.setUint64($off, $v, Endian.little)',
      WireType.i64 => 'bd.setInt64($off, $v, Endian.little)',
      WireType.char => 'bd.setUint8($off, $v)',
    };

void _emitVarRecord(ProtocolSpec spec, RecordSpec r, StringBuffer b) {
  final cls = _className(r);
  final maxSize = r.declaredMaxSize ??
      r.fields.fold<int>(0, (a, f) => a + f.maxByteSize);

  b.writeln('/// ${r.name} — variable length, ≤ $maxSize B on the wire.');
  b.writeln('/// Explicit length fields are derived from the list/byte lengths.');
  b.writeln('class $cls {');
  b.writeln('  $cls({');
  for (final f in r.fields) {
    if (_isLengthField(r, f)) continue;
    final n = _camel(f.name);
    if (f.isVariable) {
      if (_isChar(f) || f.type == WireType.u8) {
        b.writeln('    Uint8List? ${n}Raw,');
      } else {
        b.writeln('    List<int>? $n,');
      }
    } else if (f.count > 1) {
      b.writeln('    List<int>? $n,');
    } else if (f.constValue is int) {
      b.writeln('    this.$n = ${f.constValue},');
    } else {
      b.writeln('    this.$n = 0,');
    }
  }
  final inits = <String>[];
  for (final f in r.fields) {
    if (_isLengthField(r, f)) continue;
    final n = _camel(f.name);
    if (f.isVariable) {
      if (_isChar(f) || f.type == WireType.u8) {
        inits.add('${n}Raw = ${n}Raw ?? Uint8List(0)');
      } else {
        inits.add('$n = $n ?? const <int>[]');
      }
    } else if (f.count > 1) {
      inits.add('$n = $n ?? List<int>.filled(${f.count}, 0)');
    }
  }
  if (inits.isEmpty) {
    b.writeln('  });');
  } else {
    b.writeln('  })  : ${inits.join(',\n        ')};');
  }
  b.writeln();
  b.writeln('  static const int maxSize = $maxSize;');
  b.writeln();
  for (final f in r.fields) {
    if (_isLengthField(r, f)) continue;
    final n = _camel(f.name);
    final doc = f.doc != null ? '  /// ${f.doc}\n' : '';
    b.write(doc);
    if (f.isVariable) {
      if (_isChar(f) || f.type == WireType.u8) {
        b.writeln('  final Uint8List ${n}Raw;');
        if (_isChar(f)) {
          b.writeln('  String get $n => utf8FromPadded(${n}Raw);');
        }
      } else {
        b.writeln('  final List<int> $n;');
      }
    } else if (f.count > 1) {
      b.writeln('  final List<int> $n;');
    } else {
      b.writeln('  final int $n;');
    }
  }
  b.writeln();
  for (final f in r.fields) {
    if (_isLengthField(r, f)) continue;
    final n = _camel(f.name);
    if (f.sentinel != null && f.isVariable && f.type == WireType.i16) {
      b.writeln('  /// null for sentinel (detached/invalid) entries.');
      b.writeln('  List<int?> get ${n}Nullable => [');
      b.writeln('        for (final v in $n)');
      b.writeln('          if (v == tempDetached || v == tempInvalid) null else v,');
      b.writeln('      ];');
      b.writeln();
    }
    if (f.bits != null) {
      for (var i = 0; i < f.bits!.length; i++) {
        final bit = f.bits![i];
        if (bit.startsWith('_')) continue;
        b.writeln('  bool get ${_camel(bit)} => ($n & (1 << $i)) != 0;');
      }
      b.writeln();
    }
    if (f.enumName != null) {
      b.writeln('  ${_enumClass(f.enumName!)}? get ${n}Enum => '
          '${_enumClass(f.enumName!)}.fromWire($n);');
      b.writeln();
    }
  }

  // pack
  b.writeln('  /// Serializes to wire bytes. Throws [ArgumentError] if a variable');
  b.writeln('  /// field exceeds its declared max.');
  b.writeln('  Uint8List pack() {');
  for (final f in r.fields.where((f) => f.isVariable)) {
    final n = _camel(f.name);
    final lenOf = (_isChar(f) || f.type == WireType.u8) ? '${n}Raw.length' : '$n.length';
    b.writeln('    if ($lenOf > ${f.max}) {');
    b.writeln("      throw ArgumentError('${f.name} exceeds ${f.max} elements');");
    b.writeln('    }');
  }
  b.writeln('    final out = BytesBuilder();');
  for (final f in r.fields) {
    final n = _camel(f.name);
    if (_isLengthField(r, f)) {
      final owner = r.fields.firstWhere((o) => o.varLenField == f.name);
      final on = _camel(owner.name);
      final lenOf = (_isChar(owner) || owner.type == WireType.u8)
          ? '${on}Raw.length'
          : '$on.length';
      b.writeln('    out.addByte($lenOf);');
    } else if (f.isVariable) {
      if (_isChar(f) || f.type == WireType.u8) {
        b.writeln('    out.add(${n}Raw);');
      } else {
        b.writeln('    for (final v in $n) {');
        b.writeln('      out.addByte(v & 0xFF);');
        b.writeln('      out.addByte((v >> 8) & 0xFF); // little-endian i16');
        b.writeln('    }');
      }
    } else if (f.count > 1) {
      b.writeln('    out.add(Uint8List.fromList($n));');
    } else {
      switch (f.type.size) {
        case 1:
          b.writeln('    out.addByte($n & 0xFF);');
        case 2:
          b.writeln('    out.addByte($n & 0xFF);');
          b.writeln('    out.addByte(($n >> 8) & 0xFF); // little-endian');
        case 4:
          b.writeln('    out.add((ByteData(4)..setUint32(0, $n, Endian.little))');
          b.writeln('        .buffer');
          b.writeln('        .asUint8List());');
        case 8:
          b.writeln('    out.add((ByteData(8)..setUint64(0, $n, Endian.little))');
          b.writeln('        .buffer');
          b.writeln('        .asUint8List());');
      }
    }
  }
  b.writeln('    return out.toBytes();');
  b.writeln('  }');
  b.writeln();

  // unpack
  b.writeln('  /// Parses wire bytes. Throws [FormatException] on truncation or');
  b.writeln('  /// out-of-range lengths.');
  b.writeln('  static $cls unpack(Uint8List buf) {');
  b.writeln('    final bd = ByteData.sublistView(buf);');
  b.writeln('    var off = 0;');
  b.writeln('    void need(int n) {');
  b.writeln('      if (off + n > buf.length) {');
  b.writeln("        throw FormatException('${r.name}: truncated at byte \$off');");
  b.writeln('      }');
  b.writeln('    }');
  b.writeln();
  final locals = <String, String>{}; // field name -> local var
  for (final f in r.fields) {
    final n = _camel(f.name);
    if (_isLengthField(r, f)) {
      b.writeln('    need(1);');
      b.writeln('    final ${n}V = bd.getUint8(off);');
      b.writeln('    off += 1;');
      locals[f.name] = '${n}V';
    } else if (f.isVariable) {
      final lenLocal = f.varLenImplicit
          ? '(buf.length - off)'
          : locals[f.varLenField]!;
      if (!f.varLenImplicit) {
        b.writeln('    if ($lenLocal > ${f.max}) {');
        b.writeln("      throw FormatException('${r.name}.${f.name}: length over max');");
        b.writeln('    }');
      } else {
        b.writeln('    if ($lenLocal > ${f.max}) {');
        b.writeln("      throw FormatException('${r.name}.${f.name}: length over max');");
        b.writeln('    }');
      }
      if (_isChar(f) || f.type == WireType.u8) {
        b.writeln('    need($lenLocal);');
        b.writeln('    final ${n}V = Uint8List.fromList('
            'Uint8List.sublistView(buf, off, off + $lenLocal));');
        b.writeln('    off += $lenLocal;');
      } else {
        b.writeln('    need($lenLocal * 2);');
        b.writeln('    final ${n}V = <int>[');
        b.writeln('      for (var i = 0; i < $lenLocal; i++)');
        b.writeln('        bd.getInt16(off + i * 2, Endian.little),');
        b.writeln('    ];');
        b.writeln('    off += $lenLocal * 2;');
      }
      locals[f.name] = '${n}V';
    } else if (f.count > 1) {
      b.writeln('    need(${f.count});');
      b.writeln('    final ${n}V = List<int>.generate('
          '${f.count}, (i) => bd.getUint8(off + i));');
      b.writeln('    off += ${f.count};');
      locals[f.name] = '${n}V';
    } else {
      b.writeln('    need(${f.type.size});');
      b.writeln('    final ${n}V = ${_bdGet(f.type, 'off')};');
      b.writeln('    off += ${f.type.size};');
      locals[f.name] = '${n}V';
    }
  }
  b.writeln('    return $cls(');
  for (final f in r.fields) {
    if (_isLengthField(r, f)) continue;
    final n = _camel(f.name);
    if (f.isVariable && (_isChar(f) || f.type == WireType.u8)) {
      b.writeln('      ${n}Raw: ${locals[f.name]},');
    } else {
      b.writeln('      $n: ${locals[f.name]},');
    }
  }
  b.writeln('    );');
  b.writeln('  }');
  b.writeln('}');
  b.writeln();
}
