import 'spec.dart';

/// Emits protocol/gen/record_gen.h: packed structs with static size asserts,
/// CRC helpers, sentinel constants, bitfield accessors, and encode/decode
/// (fixed records) or pack/unpack (variable payloads) helpers.
///
/// Everything is `static inline` so the single header serves both the ESP-IDF
/// build and the plain-CMake host tests with no companion .c file.
String emitC(ProtocolSpec spec) {
  final b = StringBuffer();
  b.writeln(
    '/* GENERATED by tools/protogen from protocol/records.yaml — DO NOT EDIT.',
  );
  b.writeln(' * Regenerate with: dart run protogen   (CI fails on any diff)');
  b.writeln(' *');
  b.writeln(
    ' * Little-endian wire format throughout. See protocol/records.yaml for',
  );
  b.writeln(' * field semantics and design 04 §4.2 / 05 §5.6 for rationale.');
  b.writeln(' */');
  b.writeln('#ifndef BRIDGE_RECORD_GEN_H');
  b.writeln('#define BRIDGE_RECORD_GEN_H');
  b.writeln();
  b.writeln('#include <stdbool.h>');
  b.writeln('#include <stddef.h>');
  b.writeln('#include <stdint.h>');
  b.writeln('#include <string.h>');
  b.writeln();
  b.writeln('#ifdef __cplusplus');
  b.writeln('extern "C" {');
  b.writeln('#endif');
  b.writeln();

  _emitConstants(spec, b);
  _emitEnums(spec, b);
  _emitByteHelpers(b);
  _emitCrc(spec, b);

  for (final r in spec.records) {
    if (r.isFixed || (r.isControlBody && !r.hasVariableFields)) {
      _emitFixedRecord(spec, r, b);
    } else {
      _emitVarRecord(spec, r, b);
    }
  }

  b.writeln('#ifdef __cplusplus');
  b.writeln('}');
  b.writeln('#endif');
  b.writeln();
  b.writeln('#endif /* BRIDGE_RECORD_GEN_H */');
  return b.toString();
}

String _cName(RecordSpec r) =>
    r.isControlBody ? 'bridge_ctrl_${r.name}' : 'bridge_${r.name}';

String _upper(String s) => s.toUpperCase();

String _cType(WireType t) => switch (t) {
  WireType.u8 => 'uint8_t',
  WireType.i8 => 'int8_t',
  WireType.u16 => 'uint16_t',
  WireType.i16 => 'int16_t',
  WireType.u32 => 'uint32_t',
  WireType.i32 => 'int32_t',
  WireType.u64 => 'uint64_t',
  WireType.i64 => 'int64_t',
  WireType.char => 'char',
};

void _emitConstants(ProtocolSpec spec, StringBuffer b) {
  b.writeln(
    '/* ── Constants ─────────────────────────────────────────────── */',
  );
  b.writeln();
  spec.constants.forEach((name, value) {
    if (value is String) {
      b.writeln('#define BRIDGE_${_upper(name)} "$value"');
    } else if (name.startsWith('TEMP_')) {
      b.writeln('#define BRIDGE_${_upper(name)} ((int16_t)$value)');
    } else {
      b.writeln('#define BRIDGE_${_upper(name)} ($value)');
    }
  });
  b.writeln();
}

void _emitEnums(ProtocolSpec spec, StringBuffer b) {
  b.writeln(
    '/* ── Enums (wire values) ───────────────────────────────────── */',
  );
  b.writeln();
  spec.enums.forEach((name, values) {
    b.writeln('typedef enum {');
    values.forEach((k, v) {
      b.writeln('    BRIDGE_${_upper(name)}_${_upper(k)} = $v,');
    });
    b.writeln('} bridge_${name}_t;');
    b.writeln();
    // The YAML key IS the JSON spelling (06 §6.2). Emitting it here means a
    // wire value has exactly one name in C, and it is the same one Dart's
    // generated enum carries — instead of a switch someone maintains twice.
    b.writeln('static inline const char *bridge_${name}_str(int v) {');
    b.writeln('    switch (v) {');
    values.forEach((k, v) {
      b.writeln('    case $v:');
      b.writeln('        return "$k";');
    });
    b.writeln('    default:');
    b.writeln('        return "";');
    b.writeln('    }');
    b.writeln('}');
    b.writeln();
  });
}

void _emitByteHelpers(StringBuffer b) {
  b.writeln(
    '/* ── Little-endian byte access ─────────────────────────────── */',
  );
  b.writeln();
  b.writeln('''
static inline void bridge_put_u16(uint8_t *p, uint16_t v) {
    p[0] = (uint8_t)(v & 0xFFu);
    p[1] = (uint8_t)(v >> 8);
}

static inline void bridge_put_u32(uint8_t *p, uint32_t v) {
    p[0] = (uint8_t)(v & 0xFFu);
    p[1] = (uint8_t)((v >> 8) & 0xFFu);
    p[2] = (uint8_t)((v >> 16) & 0xFFu);
    p[3] = (uint8_t)(v >> 24);
}

static inline void bridge_put_u64(uint8_t *p, uint64_t v) {
    bridge_put_u32(p, (uint32_t)(v & 0xFFFFFFFFu));
    bridge_put_u32(p + 4, (uint32_t)(v >> 32));
}

static inline uint16_t bridge_get_u16(const uint8_t *p) {
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}

static inline uint32_t bridge_get_u32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

static inline uint64_t bridge_get_u64(const uint8_t *p) {
    return (uint64_t)bridge_get_u32(p) | ((uint64_t)bridge_get_u32(p + 4) << 32);
}
''');
}

void _emitCrc(ProtocolSpec spec, StringBuffer b) {
  // The emitter supports the two canonical shapes the spec declares:
  // crc16 unreflected (CCITT-FALSE) and crc32 reflected (ISO-HDLC).
  if (spec.crc16['refin'] != 0 || spec.crc16['refout'] != 0) {
    throw SpecException('crc16 emitter expects refin/refout = false');
  }
  if (spec.crc32['refin'] != 1 || spec.crc32['refout'] != 1) {
    throw SpecException('crc32 emitter expects refin/refout = true');
  }
  final poly16 = spec.crc16['poly']!;
  final poly32r = _reflect32(spec.crc32['poly']!);
  b.writeln(
    '/* ── CRC-16/CCITT-FALSE and CRC-32/ISO-HDLC ────────────────── */',
  );
  b.writeln();
  b.writeln('''
static inline uint16_t bridge_crc16_update(uint16_t crc, const uint8_t *data,
                                           size_t len) {
    for (size_t i = 0; i < len; i++) {
        crc = (uint16_t)(crc ^ ((uint16_t)data[i] << 8));
        for (int bit = 0; bit < 8; bit++) {
            crc = (uint16_t)((crc & 0x8000u)
                                 ? (uint16_t)(crc << 1) ^ 0x${poly16.toRadixString(16).toUpperCase().padLeft(4, '0')}u
                                 : (uint16_t)(crc << 1));
        }
    }
    return crc;
}

/* check("123456789") == 0x29B1 */
static inline uint16_t bridge_crc16(const uint8_t *data, size_t len) {
    return bridge_crc16_update((uint16_t)0x${spec.crc16['init']!.toRadixString(16).toUpperCase()}u, data, len);
}

static inline uint32_t bridge_crc32_update(uint32_t state, const uint8_t *data,
                                           size_t len) {
    for (size_t i = 0; i < len; i++) {
        state ^= data[i];
        for (int bit = 0; bit < 8; bit++) {
            state = (state >> 1) ^
                    (0x${poly32r.toRadixString(16).toUpperCase()}u & (uint32_t)(-(int32_t)(state & 1u)));
        }
    }
    return state;
}

/* check("123456789") == 0xCBF43926 */
static inline uint32_t bridge_crc32(const uint8_t *data, size_t len) {
    return bridge_crc32_update(0x${spec.crc32['init']!.toRadixString(16).toUpperCase()}u, data, len) ^
           0x${spec.crc32['xorout']!.toRadixString(16).toUpperCase()}u;
}
''');
}

int _reflect32(int v) {
  var r = 0;
  for (var i = 0; i < 32; i++) {
    r = (r << 1) | ((v >> i) & 1);
  }
  return r;
}

void _emitBitAccessors(RecordSpec r, FieldSpec f, StringBuffer b) {
  final rec = _upper(_cName(r).replaceFirst('bridge_', ''));
  for (var i = 0; i < f.bits!.length; i++) {
    final bit = f.bits![i];
    if (bit.startsWith('_')) continue;
    b.writeln(
      '#define BRIDGE_${rec}_${_upper(f.name)}_${_upper(bit)} (1u << $i)',
    );
  }
  for (var i = 0; i < f.bits!.length; i++) {
    final bit = f.bits![i];
    if (bit.startsWith('_')) continue;
    b.writeln('''
static inline bool ${_cName(r)}_${bit}(uint8_t ${f.name}) {
    return (${f.name} & (1u << $i)) != 0;
}''');
  }
  b.writeln();
}

void _emitCrcFn(RecordSpec r, FieldSpec f, StringBuffer b) {
  final name =
      '${_cName(r)}_${f.name == 'crc16' || f.name == 'crc32' ? 'crc' : f.name}';
  if (f.crc!.kind == 'crc16') {
    b.writeln('static inline uint16_t $name(const uint8_t *buf) {');
    b.writeln('    uint16_t c = 0xFFFFu;');
    for (final range in f.crc!.ranges) {
      b.writeln(
        '    c = bridge_crc16_update(c, buf + ${range.start}, '
        '${range.end - range.start + 1});',
      );
    }
    b.writeln('    return c;');
    b.writeln('}');
  } else {
    b.writeln('static inline uint32_t $name(const uint8_t *buf) {');
    b.writeln('    uint32_t s = 0xFFFFFFFFu;');
    for (final range in f.crc!.ranges) {
      b.writeln(
        '    s = bridge_crc32_update(s, buf + ${range.start}, '
        '${range.end - range.start + 1});',
      );
    }
    b.writeln('    return s ^ 0xFFFFFFFFu;');
    b.writeln('}');
  }
  b.writeln();
}

void _emitFixedRecord(ProtocolSpec spec, RecordSpec r, StringBuffer b) {
  final name = _cName(r);
  final upper = _upper(name.replaceFirst('bridge_', ''));
  final size =
      r.declaredSize ??
      r.fields.fold<int>(0, (a, f) => a + f.type.size * f.count * f.rows);

  b.writeln(
    '/* ── ${r.name} (${r.isControlBody ? "device_control body, " : ""}'
    '$size B) ── */',
  );
  b.writeln();
  b.writeln('#define BRIDGE_${upper}_SIZE ${size}u');
  b.writeln();
  b.writeln('typedef struct __attribute__((packed)) {');
  for (final f in r.fields) {
    final dims = StringBuffer();
    if (f.rows > 1) dims.write('[${f.rows}]');
    if (f.count > 1 || f.rows > 1) dims.write('[${f.count}]');
    final doc = f.doc != null ? ' /* ${f.doc} */' : '';
    b.writeln('    ${_cType(f.type)} ${f.name}$dims;$doc');
  }
  b.writeln('} ${name}_t;');
  b.writeln();
  b.writeln('_Static_assert(sizeof(${name}_t) == BRIDGE_${upper}_SIZE,');
  b.writeln('               "${r.name} must pack to $size bytes");');
  b.writeln();

  for (final f in r.fields.where((f) => f.bits != null)) {
    _emitBitAccessors(r, f, b);
  }
  for (final f in r.fields.where((f) => f.crc != null)) {
    _emitCrcFn(r, f, b);
  }

  // encode
  b.writeln(
    'static inline void ${name}_encode(const ${name}_t *v, '
    'uint8_t out[BRIDGE_${upper}_SIZE]) {',
  );
  for (final f in r.fields) {
    if (f.crc != null) continue; // computed last
    b.write(_fieldEncode(f));
  }
  for (final f in r.fields.where((f) => f.crc != null)) {
    final fn = '${name}_crc';
    if (f.crc!.kind == 'crc16') {
      b.writeln('    bridge_put_u16(out + ${f.offset}, $fn(out));');
    } else {
      b.writeln('    bridge_put_u32(out + ${f.offset}, $fn(out));');
    }
  }
  b.writeln('}');
  b.writeln();

  // decode
  final hasCrc = r.fields.any((f) => f.crc != null);
  b.writeln(
    '/* Fills *v from the wire bytes${hasCrc ? '; returns whether the CRC matched' : ''}. '
    'Never rejects on version. */',
  );
  b.writeln(
    'static inline ${hasCrc ? 'bool' : 'void'} ${name}_decode('
    'const uint8_t *buf, ${name}_t *v) {',
  );
  for (final f in r.fields) {
    b.write(_fieldDecode(f));
  }
  if (hasCrc) {
    final f = r.fields.firstWhere((f) => f.crc != null);
    b.writeln('    return v->${f.name} == ${name}_crc(buf);');
  }
  b.writeln('}');
  b.writeln();

  if (r.name == 'session_header') {
    b.writeln('''
static inline bool bridge_session_header_magic_ok(const bridge_session_header_t *v) {
    return memcmp(v->magic, BRIDGE_SESSION_MAGIC, 4) == 0;
}
''');
  }
}

String _fieldEncode(FieldSpec f) {
  final off = f.offset!;
  final b = StringBuffer();
  if (f.type == WireType.char || (f.type == WireType.u8 && f.count > 1)) {
    final total = f.type.size * f.count * f.rows;
    b.writeln(
      '    memcpy(out + $off, ${f.rows > 1 ? 'v->${f.name}[0]' : 'v->${f.name}'}, $total);',
    );
    return b.toString();
  }
  if (f.count == 1) {
    b.writeln(
      _scalarEncode(f.type, 'out + $off', 'v->${f.name}', direct: 'out[$off]'),
    );
  } else {
    b.writeln('    for (size_t i = 0; i < ${f.count}; i++) {');
    b.writeln(
      _scalarEncode(
        f.type,
        'out + $off + i * ${f.type.size}',
        'v->${f.name}[i]',
        direct: 'out[$off + i]',
        indent: '    ',
      ),
    );
    b.writeln('    }');
  }
  return b.toString();
}

String _scalarEncode(
  WireType t,
  String ptr,
  String src, {
  required String direct,
  String indent = '',
}) {
  return switch (t) {
    WireType.u8 => '$indent    $direct = $src;',
    WireType.i8 => '$indent    $direct = (uint8_t)$src;',
    WireType.u16 => '$indent    bridge_put_u16($ptr, $src);',
    WireType.i16 => '$indent    bridge_put_u16($ptr, (uint16_t)$src);',
    WireType.u32 => '$indent    bridge_put_u32($ptr, $src);',
    WireType.i32 => '$indent    bridge_put_u32($ptr, (uint32_t)$src);',
    WireType.u64 => '$indent    bridge_put_u64($ptr, $src);',
    WireType.i64 => '$indent    bridge_put_u64($ptr, (uint64_t)$src);',
    WireType.char => '$indent    $direct = (uint8_t)$src;',
  };
}

String _fieldDecode(FieldSpec f) {
  final off = f.offset!;
  final b = StringBuffer();
  if (f.type == WireType.char || (f.type == WireType.u8 && f.count > 1)) {
    final total = f.type.size * f.count * f.rows;
    b.writeln(
      '    memcpy(${f.rows > 1 ? 'v->${f.name}[0]' : 'v->${f.name}'}, buf + $off, $total);',
    );
    return b.toString();
  }
  if (f.count == 1) {
    b.writeln(
      _scalarDecode(f.type, 'buf + $off', 'v->${f.name}', direct: 'buf[$off]'),
    );
  } else {
    b.writeln('    for (size_t i = 0; i < ${f.count}; i++) {');
    b.writeln(
      _scalarDecode(
        f.type,
        'buf + $off + i * ${f.type.size}',
        'v->${f.name}[i]',
        direct: 'buf[$off + i]',
        indent: '    ',
      ),
    );
    b.writeln('    }');
  }
  return b.toString();
}

String _scalarDecode(
  WireType t,
  String ptr,
  String dst, {
  required String direct,
  String indent = '',
}) {
  return switch (t) {
    WireType.u8 => '$indent    $dst = $direct;',
    WireType.i8 => '$indent    $dst = (int8_t)$direct;',
    WireType.u16 => '$indent    $dst = bridge_get_u16($ptr);',
    WireType.i16 => '$indent    $dst = (int16_t)bridge_get_u16($ptr);',
    WireType.u32 => '$indent    $dst = bridge_get_u32($ptr);',
    WireType.i32 => '$indent    $dst = (int32_t)bridge_get_u32($ptr);',
    WireType.u64 => '$indent    $dst = bridge_get_u64($ptr);',
    WireType.i64 => '$indent    $dst = (int64_t)bridge_get_u64($ptr);',
    WireType.char => '$indent    $dst = (char)$direct;',
  };
}

void _emitVarRecord(ProtocolSpec spec, RecordSpec r, StringBuffer b) {
  final name = _cName(r);
  final upper = _upper(name.replaceFirst('bridge_', ''));
  final maxSize =
      r.declaredMaxSize ??
      r.fields.fold<int>(0, (a, f) => a + f.maxByteSize) +
          (r.fields.any((f) => f.varLenImplicit) ? 0 : 0);

  b.writeln('/* ── ${r.name} (variable, ≤ $maxSize B on the wire) ── */');
  b.writeln();
  b.writeln('#define BRIDGE_${upper}_MAX_SIZE ${maxSize}u');
  b.writeln();
  b.writeln('typedef struct {');
  for (final f in r.fields) {
    final doc = f.doc != null ? ' /* ${f.doc} */' : '';
    if (f.isVariable) {
      b.writeln('    ${_cType(f.type)} ${f.name}[${f.max}];$doc');
      if (f.varLenImplicit) {
        b.writeln('    uint8_t ${f.name}_len; /* elements actually present */');
      }
    } else if (f.count > 1) {
      b.writeln('    ${_cType(f.type)} ${f.name}[${f.count}];$doc');
    } else {
      b.writeln('    ${_cType(f.type)} ${f.name};$doc');
    }
  }
  b.writeln('} ${name}_t;');
  b.writeln();

  for (final f in r.fields.where((f) => f.bits != null)) {
    _emitBitAccessors(r, f, b);
  }

  String lenExpr(FieldSpec f) =>
      f.varLenImplicit ? 'v->${f.name}_len' : 'v->${f.varLenField}';

  // pack
  b.writeln(
    '/* Serializes *v; returns the wire length, or -1 if a length field',
  );
  b.writeln(' * exceeds its max or cap is too small. */');
  b.writeln(
    'static inline int ${name}_pack(const ${name}_t *v, uint8_t *out, '
    'size_t cap) {',
  );
  for (final f in r.fields.where((f) => f.isVariable)) {
    b.writeln('    if (${lenExpr(f)} > ${f.max}) {');
    b.writeln('        return -1;');
    b.writeln('    }');
  }
  b.writeln('    size_t off = 0;');
  b.writeln('    size_t need = 0;');
  final fixedSize = r.fields
      .where((f) => !f.isVariable)
      .fold<int>(0, (a, f) => a + f.type.size * f.count);
  b.write('    need = ${fixedSize}u');
  for (final f in r.fields.where((f) => f.isVariable)) {
    b.write(' + (size_t)${lenExpr(f)} * ${f.type.size}u');
  }
  b.writeln(';');
  b.writeln('    if (cap < need) {');
  b.writeln('        return -1;');
  b.writeln('    }');
  for (final f in r.fields) {
    if (f.isVariable) {
      if (f.type.size == 1) {
        b.writeln('    memcpy(out + off, v->${f.name}, ${lenExpr(f)});');
        b.writeln('    off += ${lenExpr(f)};');
      } else {
        b.writeln('    for (size_t i = 0; i < ${lenExpr(f)}; i++) {');
        b.writeln(
          '        bridge_put_u16(out + off, (uint16_t)v->${f.name}[i]);',
        );
        b.writeln('        off += 2;');
        b.writeln('    }');
      }
    } else if (f.count > 1) {
      b.writeln('    memcpy(out + off, v->${f.name}, ${f.count});');
      b.writeln('    off += ${f.count};');
    } else {
      switch (f.type.size) {
        case 1:
          b.writeln('    out[off++] = (uint8_t)v->${f.name};');
        case 2:
          b.writeln('    bridge_put_u16(out + off, (uint16_t)v->${f.name});');
          b.writeln('    off += 2;');
        case 4:
          b.writeln('    bridge_put_u32(out + off, (uint32_t)v->${f.name});');
          b.writeln('    off += 4;');
        case 8:
          b.writeln('    bridge_put_u64(out + off, (uint64_t)v->${f.name});');
          b.writeln('    off += 8;');
      }
    }
  }
  b.writeln('    return (int)off;');
  b.writeln('}');
  b.writeln();

  // unpack
  b.writeln(
    '/* Parses len wire bytes into *v; returns bytes consumed or -1 on',
  );
  b.writeln(' * truncation / out-of-range lengths. */');
  b.writeln(
    'static inline int ${name}_unpack(const uint8_t *buf, size_t len, '
    '${name}_t *v) {',
  );
  b.writeln('    size_t off = 0;');
  for (final f in r.fields) {
    if (f.isVariable) {
      final n = f.varLenImplicit
          ? '(len - off)'
          : '(size_t)v->${f.varLenField}${f.type.size == 2 ? ' * 2u' : ''}';
      if (f.varLenImplicit) {
        b.writeln('    if (len - off > ${f.max}) {');
        b.writeln('        return -1;');
        b.writeln('    }');
        b.writeln('    v->${f.name}_len = (uint8_t)(len - off);');
      } else {
        b.writeln(
          '    if (v->${f.varLenField} > ${f.max} || len < off + $n) {',
        );
        b.writeln('        return -1;');
        b.writeln('    }');
      }
      if (f.type.size == 1) {
        b.writeln('    memcpy(v->${f.name}, buf + off, $n);');
        b.writeln('    off += $n;');
      } else {
        b.writeln(
          '    for (size_t i = 0; i < (size_t)v->${f.varLenField}; i++) {',
        );
        b.writeln(
          '        v->${f.name}[i] = (int16_t)bridge_get_u16(buf + off);',
        );
        b.writeln('        off += 2;');
        b.writeln('    }');
      }
    } else {
      final sz = f.type.size * f.count;
      b.writeln('    if (len < off + ${sz}u) {');
      b.writeln('        return -1;');
      b.writeln('    }');
      if (f.count > 1) {
        b.writeln('    memcpy(v->${f.name}, buf + off, ${f.count});');
        b.writeln('    off += ${f.count};');
      } else {
        switch (f.type.size) {
          case 1:
            final cast = f.type == WireType.i8
                ? '(int8_t)'
                : f.type == WireType.char
                ? '(char)'
                : '';
            b.writeln('    v->${f.name} = ${cast}buf[off++];');
          case 2:
            final cast = f.type.signed ? '(int16_t)' : '';
            b.writeln('    v->${f.name} = ${cast}bridge_get_u16(buf + off);');
            b.writeln('    off += 2;');
          case 4:
            final cast = f.type.signed ? '(int32_t)' : '';
            b.writeln('    v->${f.name} = ${cast}bridge_get_u32(buf + off);');
            b.writeln('    off += 4;');
          case 8:
            final cast = f.type.signed ? '(int64_t)' : '';
            b.writeln('    v->${f.name} = ${cast}bridge_get_u64(buf + off);');
            b.writeln('    off += 8;');
        }
      }
    }
  }
  b.writeln('    return (int)off;');
  b.writeln('}');
  b.writeln();
}
